<?php

/**
 * Implements hook_menu()
 */
function realia_feature_menu() {
  $items = array();

  return $items;
}


/**
 * Implements hook_realia_features()
 * @return array
 */
function realia_feature_realia_features() {
  return array('realia_f_feature' => array('weight' => 8));
}

/**
 * Implements hook_node_info().
 * @return array
 */
function realia_feature_node_info() {

  $items = array(
    'features' => array(
      'name' => t('Features'),
      'base' => 'node_content',
      'description' => t('Features of the website'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );

  return $items;
}
