<?php

/**
 * Implements hook_menu()
 */
function realia_property_menu() {
  $items = array();

  return $items;
}

/**
 * Implements hook_init()
 */
function realia_property_init() {

  // revert all features
  if (drupal_is_front_page() && variable_get('realia_revert', 0) == 1) {
    variable_set('realia_revert', 2);
    features_revert();
  }
}

/**
 * Implements hook_realia_features()
 * @return array
 */
function realia_property_realia_features() {
  return array('realia_f_property' => array('weight' => 1));
}

/**
 * Implements hook_node_info().
 * @return array
 */
function realia_property_node_info() {
  // @todo - rename to property
  $items = array(
      'apartment' => array(
          'name' => t('Property'),
          'base' => 'node_content',
          'description' => t('Apartments, Houses, Condos ...'),
          'has_title' => '1',
          'title_label' => t('Title'),
          'help' => '',
      ),
  );

  return $items;
}

/**
 * Implements hook_entity_info_later
 * @param $info
 */
function realia_property_entity_info_alter(&$info) {
  $info['node']['view modes']['full']['custom settings'] = TRUE;
}

/**
 * [realia_form_alter to customize the city option in the select box by "G2T: Developer"]
 */
function realia_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form") {
    switch ($form['#id']) {
      case "views-exposed-form-communities-page-1":
        $form = exposedViewFilterCommPage_1($form);
        break;
    }
  }
}

/**
 * [exposedViewFilterCommPage_1 description]
 * @param  [type] $form [description]
 * @return [type]       [description]
 */
function exposedViewFilterCommPage_1($form) {
  // $form['city']['#type'] = "select";
  // $form['city']['#size'] = null;
  // $qry = db_select('location', 'l')
  //         ->fields('l', array('city'))
  //         ->condition('l.city', '', '!=')
  //         ->distinct();
  // $qryEx = $qry->execute();
  // $cities = array();
  // while ($qry = $qryEx->fetchObject()) {
  //   $tmp = ereg_replace('[^A-Za-z?![:space:]]', '', trim(trim($qry->city, ',')));
  //   $cities[t($tmp)] = t($tmp);
  // }
  // sort($cities);
  // $city = array('' => t('- Any -'));
  // foreach ($cities as $key => $val) {
  //   $city[$key] = $val;
  // }
  // $form['city']['#options'] = $city;
  // $form['city']['#default_value'] = $form['city']['#options']['All'];
  //
  // $tmp = array();
  // foreach ($form['#info'] as $key => $val) {
  //   $tmp = str_replace('filter-', '', $key);
  //   $form[$tmp]['#id'] = drupal_html_id($key);
  // }
  return $form;
}
