<?php

function drealty_office_entity_info() {
  $entities = array();
  $entities['drealty_office'] = array(
    'label' => t('Drealty Office'),
    'plural label' => t('Drealty Offices'),
    'entity class' => 'DrealtyOffice',
    'controller class' => 'DrealtyOfficeController',
    'base table' => 'drealty_office',
    'uri callback' => 'entity_class_uri',
    'fieldable' => TRUE,
    'view modes' => array(
      'full' => array(
        'label' => 'Full View',
        'custom settings' => FALSE,
      ),
      'search' => array(
        'label' => 'Search View',
        'custom settings' => TRUE,
      ),
      'list' => array(
        'label' => 'List View',
        'custom settings' => TRUE,
      ),
      'gallery' => array(
        'label' => 'Gallery View',
        'custom settings' => TRUE,
      ),
    ),
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
      'bundle' => 'type',
    ),
    'admin ui' => array(
      'path' => 'admin/content/drealty_offices',
      'file' => 'includes/drealty.office.admin.inc',
      'controller class' => 'DrealtyOfficeUIController',
      'menu_wildcard' => '%drealty_office',
    ),
    'module' => 'drealty_office',
    'access callback' => 'drealty_office_access',
    'bundles' => array(
      'drealty_office' => array(
        'label' => 'Drealty Office',
        'admin' => array(
        'path' => 'admin/drealty/drealty_offices/manage',
        'access arguments' => array('administer drealty_offices'),
      ),
      ),
    ),
  );
  
  return $entities;
}


function drealty_office_menu() {
    $items = array();
  $items['admin/drealty/drealty_offices'] = array(
    'title' => 'Manage Drealty Office Entity Fields',
    'description' => 'Manage the Drealty Office.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drealty_office_manage_form'),
    'access arguments' => array('access drealty admin'),
    'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}

function drealty_office_create($values = array()) {
  return entity_get_controller('drealty_office')->create($values);
}

function drealty_office_manage_form($form, &$form_state) {
  $form = array();
  return $form;
}


/**
 * Fetch a listing object.
 *
 * @param $id
 *   Integer specifying the listing id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $dmealty_listing object or FALSE if it cannot be loaded.
 *
 * @see drealty_listing_load_multiple()
 */
function drealty_office_load($id, $reset = FALSE) {
  $offices = drealty_office_load_multiple(array($id), array(), $reset);
  return reset($offices);
}

/**
 * Load multiple profiles based on certain conditions.
 *
 * @param $ids
 *   An array of drealty_listing IDs.
 * @param $conditions
 *   An array of conditions to match against the {drealty_listing} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of drealty_listing objects, indexed by pid.
 *
 * @see entity_load()
 * @see drealty_listing_load()
 */
function drealty_office_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('drealty_office', $ids, $conditions, $reset);
}

function drealty_office_view($listing, $view_mode = 'full', $langcode = NULL, $page = NULL) {

  return entity_get_controller('drealty_office')->view(array($listing), $view_mode, $langcode, $page);
}

function drealty_office_access($op, $office = NULL, $account = NULL) {
  if (user_access('administer drealty_office', $account)) {
    return TRUE;
  }

  if ($op == 'create' || $op == 'update') {
    $op = 'edit';
  }

  $access = module_invoke_all('drealty_office_access', $op, $office, $account);

  // Only grant access if at least one module granted access and no one denied
  // access.
  if (in_array(FALSE, $access, TRUE)) {
    return FALSE;
  } elseif (in_array(TRUE, $access, TRUE)) {
    return TRUE;
  }
  return FALSE;
}