<?php

/**
 * Implements hook_menu().
 */
function gmap3_tools_menu() {
  $items = array();

  $items['gmap3_tools/example'] = array(
    'title' => 'Gmap3 Tools examples',
    'page callback' => 'gmap3_tools_example',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Example callback.
 */
function gmap3_tools_example() {
  // You need to include gmap3_tools.inc file first in order to use it.
  module_load_include('inc', 'gmap3_tools');

  // Default map example.
  gmap3_tools_add_map(array('mapId' => 'map-canvas-01'));
  $output = t('Map example 01 (default map):') . '<div id="map-canvas-01" style="width:400px; height:300px"></div>';

  $output .= '<br/>';

  // Map example with some custom options and 2 markers.
  gmap3_tools_add_map(array(
    'mapId' => 'map-canvas-02',
    'mapOptions' => array(
      'centerX' => -34.397,
      'centerY' => 150.644,
      'zoom' => 8,
    ),
    'markers' => array(
      gmap3_tools_create_marker(-35, 150, '<div class=xxx style="background-color: red !important;">Marker with info window</div>', '<div class=xxx style="background-color: red !important";>Marker info window content.</div>'),
      gmap3_tools_create_marker(-35, 150.5, 'Marker without info window'),
    ),
    'gmap3ToolsOptions' => array(
      'defaultMarkersPosition' => GMAP3_TOOLS_DEFAULT_MARKERS_POSITION_CENTER,
    ),
  ));
  $output .= t('Map example 02 with custom markers:') . '<div id="map-canvas-02" style="width:500px; height:400px"></div>';

  $output .= '<br/>';

  // Map example 03 with custom icon shadow for all markers and custom marker
  // icons.
  gmap3_tools_add_map(array(
    'mapId' => 'map-canvas-03',
    'mapOptions' => array(
      'centerX' => -34.397,
      'centerY' => 150.644,
      'zoom' => 8,
    ),
    'markers' => array(
      gmap3_tools_create_marker(-35, 149.5, 'Marker with default icon but custom default shadow.'),
      // Last parameter array will be used for marker options for this marker.
      // See below also for global markerOptions parameter.
      gmap3_tools_create_marker(-35, 150, 'Marker with blue druplicon icon.', NULL, array(
        'icon' => file_create_url(drupal_get_path('module', 'gmap3_tools') . '/images/druplicon-blue.png'),
      )),
      gmap3_tools_create_marker(-35, 150.5, 'Marker with green druplicon icon.', NULL, array(
        'icon' => file_create_url(drupal_get_path('module', 'gmap3_tools') . '/images/druplicon-green.png'),
      )),
    ),
    // MarkerOptions object for all markers in this map.
    // You should be able to use all properties from google.maps.MarkerOptions
    // object specification.
    // See https://developers.google.com/maps/documentation/javascript/reference#MarkerOptions
    'markerOptions' => array(
      // Set custom shadow for all icons.
      'shadow' => file_create_url(drupal_get_path('module', 'gmap3_tools') . '/images/druplicon-shadow.png'),
    ),
    'gmap3ToolsOptions' => array(
      'defaultMarkersPosition' => GMAP3_TOOLS_DEFAULT_MARKERS_POSITION_CENTER,
    ),
  ));
  $output .= t('Map example 03 with custom icon shadow for all markers and custom marker icons.') . '<div id="map-canvas-03" style="width:500px; height:400px"></div>';

  return $output;
}
